apiVersion: v1
kind: Pod
metadata:
  name: two-containers-pod
  labels:
    app: two-containers
spec:
  containers:
  - name: container-one
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
  - name: container-two
    image: nginx
    ports:
    - containerPort: 50
    volumeMounts:
    - name: html-volume-2
      mountPath: /usr/share/nginx/html
  volumes:
  - name: html-volume
    configMap:
      name: html-one
  - name: html-volume-2
    configMap:
      name: html-two
